version: '3'
services:
  ds:
    image: node:latest
    container_name: cra
    hostname: cra
    working_dir: "/home/node/app"
    # build:
    #   context: .
    #   dockerfile: ./notebooks/Dockerfile
    env_file:
      - .env
    ports:
      - 8800:8800
    volumes:
      - .:/home/node/app
    command: "tail -F anything"
    # command: "npm install npm start --port 8800"
    restart: unless-stopped